version: '3'

services:
    consul:
        container_name: consul
        image: docker.io/bitnami/consul:1-debian-10
        volumes:
          - ./ConfigCompose/consul:/bitnami/consul
        ports:
          - '8500:8500'

    vault:
        container_name: vault
        image: vault
        volumes:
            - ./ConfigCompose:/vault/config:rw
            - ./ConfigCompose/data:/data
        cap_add:
          - IPC_LOCK
        command: vault server -config=/vault/config/vault.json
        environment:
            VAULT_ADDR: 'http://0.0.0.0:8200'
        ports:
          - '8200:8200'
        depends_on:
            - consul

    mongodb:
      container_name: mongodb
      image: mongo:4.2
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: Uther
        MONGO_INITDB_ROOT_PASSWORD: ArthasLichKing

    rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.8.6-management-alpine
      restart: always
      ports:
        - 15672:15672
        - 5672:5672
      environment:
        RABBITMQ_DEFAULT_USER: illidan
        RABBITMQ_DEFAULT_PASS: SylvanaWindRunner